name: ocr-engine-api
services:
- name: ocr-api
  source_dir: /
  github:
    repo: Kojo360/Ocr-engine
    branch: main
    deploy_on_push: true
  build_command: |
    apt-get update && 
    apt-get install -y tesseract-ocr poppler-utils libgl1-mesa-glx libglib2.0-0 && 
    pip install --no-cache-dir -r requirements.production.txt
  run_command: python start_production.py
  environment_slug: python
  instance_count: 1
  instance_size_slug: basic-s
  http_port: 8000
  health_check:
    http_path: /health
    initial_delay_seconds: 60
    period_seconds: 30
    timeout_seconds: 15
    success_threshold: 1
    failure_threshold: 5
  envs:
  - key: HOST
    value: "0.0.0.0"
  - key: PORT
    value: "8000"
  - key: TESSERACT_CMD
    value: "/usr/bin/tesseract"
  - key: POPPLER_PATH
    value: "/usr/bin"
  - key: SCAN_DIR
    value: "/tmp/incoming-scan"
  - key: FULLY_INDEXED_DIR
    value: "/tmp/fully_indexed"
  - key: PARTIAL_INDEXED_DIR
    value: "/tmp/partially_indexed"
  - key: FAILED_DIR
    value: "/tmp/failed"
  - key: LOG_LEVEL
    value: "INFO"
  - key: OCR_DPI
    value: "300"
  - key: MAX_RETRIES
    value: "2"
  - key: RETRY_DELAY
    value: "0.5"
  - key: BATCH_DELAY
    value: "0.3"
  - key: PROCESS_DELAY
    value: "2"
  - key: PYTHONUNBUFFERED
    value: "1"

# Uncomment to add managed database
# databases:
# - name: ocr-database
#   engine: MYSQL
#   version: "8"
#   size: db-s-1vcpu-1gb

# Uncomment to add static site for documentation
# static_sites:
# - name: ocr-docs
#   source_dir: /docs
#   build_command: echo "No build needed"
#   output_dir: /docs
