name: ocr-engine-api
services:
- name: ocr-api
  source_dir: /
  github:
    repo: Kojo360/Ocr-engine
    branch: main
    deploy_on_push: true
  run_command: python ocr_watcher.py
  environment_slug: python
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8000
  health_check:
    http_path: /health
    initial_delay_seconds: 30
    period_seconds: 30
    timeout_seconds: 10
    success_threshold: 1
    failure_threshold: 3
  envs:
  - key: HOST
    value: "0.0.0.0"
  - key: PORT
    value: "8080"
  - key: TESSERACT_CMD
    value: "/usr/bin/tesseract"
  - key: POPPLER_PATH
    value: "/usr/bin"
  - key: SCAN_DIR
    value: "/app/incoming-scan"
  - key: FULLY_INDEXED_DIR
    value: "/app/fully_indexed"
  - key: PARTIAL_INDEXED_DIR
    value: "/app/partially_indexed"
  - key: FAILED_DIR
    value: "/app/failed"
  - key: LOG_LEVEL
    value: "INFO"
  - key: OCR_DPI
    value: "600"
  - key: MAX_RETRIES
    value: "3"
  - key: RETRY_DELAY
    value: "1.0"
  - key: BATCH_DELAY
    value: "0.5"
  - key: PROCESS_DELAY
    value: "5"

# Uncomment to add managed database
# databases:
# - name: ocr-database
#   engine: MYSQL
#   version: "8"
#   size: db-s-1vcpu-1gb

# Uncomment to add static site for documentation
# static_sites:
# - name: ocr-docs
#   source_dir: /docs
#   build_command: echo "No build needed"
#   output_dir: /docs
