version: "3.8"

services:
  ocr_watcher:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ocr_watcher
    restart: unless-stopped
    environment:
      PYTHONUNBUFFERED: "1"
      TZ: "Africa/Lagos"
      HOST: "0.0.0.0"
      PORT: "8000"
      SCAN_DIR: "/app/incoming-scan"
      FULLY_INDEXED_DIR: "/app/fully_indexed"
      PARTIAL_INDEXED_DIR: "/app/partially_indexed"
      FAILED_DIR: "/app/failed"
      DEBUG_DIR: "/app/debug"
      LOG_DIR: "/app/logs"
    ports:
      - "8000:8000"
    volumes:
      - ./incoming-scan:/app/incoming-scan
      - ./fully_indexed:/app/fully_indexed
      - ./partially_indexed:/app/partially_indexed
      - ./failed:/app/failed
      - ./debug:/app/debug
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 5

